### ISSUE TITLE
Email and name mangled together

### ISSUE THREAD

**Issue by petamaj** [PRL-PRG/ghgrabber#6]
https://github.com/andreeni/tr69_fitnesse/commit/dd50cda73ab567c34032757eb10cd203ed154143

Produces:

```
"dd50cda73ab567c34032757eb10cd203ed154143","GHERGU, GRATIELA (GRATIELA)" Gratiela.Ghergu@alcatel-lucent.com","1354811115","GHERGU, GRATIELA (GRATIELA)" Gratiela.Ghergu@alcatel-lucent.com","1354811115",""
```

> note that somehow there is user name before the email as well and there is the single double quote between them which confuses the csv reader. We still end up with the proper number of columns though, but we fail the `std::stoull`

**Comment by petamaj** [comment]
Another weird name mangle:

https://github.com/jeffreytgilbert/webstormProjects/commit/84ccd866e1e3339e260bf3e81ce1cdac6ec74645

Reports:

```
"84ccd866e1e3339e260bf3e81ce1cdac6ec74645","jeffreytgilbert" = "gmail.com","1376530967","jeffreytgilbert" = "gmail.com","1376530967","HEAD -> master, origin/master, origin/HEAD"
```

**Comment by kondziu** [comment]
Trying to fix it. Does this output look good to you?

from andreeni/tr69_fitnesse
```
dd50cda73ab567c34032757eb10cd203ed154143,"GHERGU, GRATIELA (GRATIELA)\" Gratiela.Ghergu@alcatel-lucent.com","1354811115","GHERGU, GRATIELA (GRATIELA)\" Gratiela.Ghergu@alcatel-lucent.com","1354811115",
```

from jeffreytgilbert/WebstormProjects:
```
84ccd866e1e3339e260bf3e81ce1cdac6ec74645,"jeffreytgilbert\" = \"gmail.com","1376530967","jeffreytgilbert\" = \"gmail.com","1376530967","HEAD -> master, origin/master, origin/HEAD"
```

**Comment by petamaj** [comment]
It would not confuse the joiner script anymore, although I would assume in
the second example the proper answer should be `"\"jeffreygilbert\" = \"
gmail.com\""`. I haven't checked the actual git log though... If he really
has such a **** username as the escaping you suggest, then it definitely
looks correct to me.

**Comment by kondziu** [comment]
Here's git log for that one:
```
commit 84ccd866e1e3339e260bf3e81ce1cdac6ec74645
Author: Jeffrey Gilbert <jeffreytgilbert" = "gmail.com>
Date:   Wed Aug 14 20:42:47 2013 -0500

    Working data retrieval
```

**Comment by petamaj** [comment]
Yeah… The what you propose is absolutely correct. 

 

We should propel this one to the first place of the set of people earlier mentioned by Jan wrt filenames😊

**Comment by kondziu** [comment]
The world being what it is, we should make due with a programmatic fix instead.
